import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data: scraperData, isLoading } = trpc.useQuery(['teams.getAll'], {
    onSuccess(data) {
      console.log(data);
    },
  });

  if (!scraperData || isLoading) return <p>Loading.....</p>;

  return (
    <>
      <Head>
        <title>TeamMate - The Ultimate Sport Schedule Viewer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto my-12 max-w-3xl">
        <h1 className="text-2xl font-semibold">TeamMate</h1>
      </main>
    </>
  );
};

export default Home;
